# based on https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Run tests in Answers

on:
  push:
    branches:
      - main
      - add_ci_pipeline
  pull_request:

concurrency:
  # For pull requests, cancel all currently-running jobs for this workflow
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [8.0.x]
        include:
          - dotnet-version: 8.0.x
            framework: net8.0

    steps:
      - uses: actions/checkout@v3